version: "3.1"
services:
  control_sys:
    container_name: control_sys
    build:
      context: .
    restart: "unless-stopped"
    network_mode: "host"
    privileged: true
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
